import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import Link from "next/link";
import { Play, ExternalLink, AlertTriangle, Github } from "lucide-react";

export default function DemoPage() {
  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="max-w-4xl mx-auto space-y-8">
        <div className="text-center space-y-4">
          <h1 className="text-4xl md:text-5xl font-bold">Demo Videos</h1>
          <p className="text-xl text-muted-foreground">
            See the system in action or try it yourself
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Interactive Demo</CardTitle>
            <CardDescription>
              Experience the system live with your own camera
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              The best way to experience Describe My Environment is to try it
              yourself! The interactive test page allows you to see real-time object
              detection, tracking, and AI narration powered by your camera feed.
            </p>
            <Alert
              variant="warning"
              className="bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800"
            >
              <AlertTriangle className="h-4 w-4 text-amber-600 dark:text-amber-400" />
              <AlertTitle className="text-amber-800 dark:text-amber-300 font-semibold">
                Local Setup Required
              </AlertTitle>
              <AlertDescription className="text-amber-700 dark:text-amber-400/90">
                Due to the computational requirements of real-time AI processing,
                the interactive test page is only available when running the application
                locally. Clone the repository and follow the setup instructions to try it yourself.
              </AlertDescription>
            </Alert>
            <div className="flex flex-col sm:flex-row gap-3">
              <Button size="lg" className="w-full sm:w-auto" asChild>
                <a
                  href="https://github.com/sorryshady/stats-507-assignment"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Github className="w-4 h-4 mr-2" />
                  View Source Code
                </a>
              </Button>
              {process.env.NODE_ENV === "development" && (
                <Link href="/test">
                  <Button size="lg" variant="outline" className="w-full sm:w-auto">
                    <Play className="w-4 h-4 mr-2" />
                    Try Interactive Demo
                  </Button>
                </Link>
              )}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Video Demonstrations</CardTitle>
            <CardDescription>
              Watch recorded demonstrations of key features
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-2">
              <h3 className="font-semibold">Real-Time Object Detection</h3>
              <p className="text-sm text-muted-foreground">
                See how the system detects and tracks multiple objects
                simultaneously with bounding boxes and confidence scores.
              </p>
              <div className="aspect-video bg-muted rounded-lg flex items-center justify-center">
                <p className="text-muted-foreground">
                  Video placeholder - Add your demo video here
                </p>
              </div>
            </div>

            <div className="space-y-2">
              <h3 className="font-semibold">Hazard Detection & Alerts</h3>
              <p className="text-sm text-muted-foreground">
                Watch how the system identifies approaching hazards and provides
                real-time alerts.
              </p>
              <div className="aspect-video bg-muted rounded-lg flex items-center justify-center">
                <p className="text-muted-foreground">
                  Video placeholder - Add your demo video here
                </p>
              </div>
            </div>

            <div className="space-y-2">
              <h3 className="font-semibold">AI Narration</h3>
              <p className="text-sm text-muted-foreground">
                Experience natural language scene descriptions generated by the
                AI system.
              </p>
              <div className="aspect-video bg-muted rounded-lg flex items-center justify-center">
                <p className="text-muted-foreground">
                  Video placeholder - Add your demo video here
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Getting Started (Local Setup)</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm text-muted-foreground mb-4">
              To run the interactive test page locally:
            </p>
            <ol className="list-decimal list-inside space-y-2 text-muted-foreground">
              <li>Clone the repository from GitHub</li>
              <li>Set up Python virtual environment and install backend dependencies</li>
              <li>Start the backend server on port 8000</li>
              <li>Ensure Ollama is running with Llama 3.2 3B model</li>
              <li>Run <code className="bg-muted px-2 py-1 rounded text-xs">npm run dev</code> in the frontend directory</li>
              <li>Navigate to the Test page and click &quot;Start Camera&quot;</li>
              <li>Watch real-time detections and try the narration feature</li>
            </ol>
            <Button variant="outline" className="w-full sm:w-auto" asChild>
              <a
                href="https://github.com/sorryshady/stats-507-assignment"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Github className="w-4 h-4 mr-2" />
                View Source Code & Setup Instructions
              </a>
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
